version: '3.7'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - 3333:3333
  grafana:
    container_name: grafana-simple-json-datasource
    platform: linux/amd64
    image: grafana/grafana-enterprise:${GF_VERSION:-main}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource, grafana-simple-json-datasource
